<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IoTPlatform.Core\IoTPlatform.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HslCommunication" Version="13.0.0" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
